### ISSUE TITLE
Error on ListingResponseModel<AssetModel>.GetNextPage()

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/content-management-sdk-net#19]
Using .NET CM API 1.2.0, I've created a .NET application and on an ASPX page set Async="true." In the code behind, I have the following:

```
protected async void Page_Load(object sender, EventArgs e)
{
            ContentManagementOptions options = new ContentManagementOptions
            {
                ApiKey = "<my key>",
                ProjectId = "<my project>"
            };
            ContentManagementClient client = new ContentManagementClient(options);

            var assets = await client.ListAssetsAsync();
            var nextpage = await assets.GetNextPage();
}
```
In a project with over 100 assets, I get the error found in [error.txt](https://github.com/Kentico/content-management-sdk-net/files/2295771/error.txt) when reaching the GetNextPage() method- if I remove the call everything is fine.

**Comment by ivanaliptakova** [comment]
fixed in #20
