### ISSUE TITLE
Fix HasNextPage

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/content-management-sdk-net#2]
https://github.com/Kentico/content-management-sdk-net/commit/60468963ca54c95b8bfb28bed2ce5c15a70b4cb4#commitcomment-26275536

**Comment by JanLenoch** [comment]
Fixed via https://github.com/Kentico/content-management-sdk-net/commit/6e68137da2e55e46590a9d380b21fa48c5cec7f9
