### ISSUE TITLE
ContentManagementHttpClient Re-use of HttpRequestMessage

### ISSUE THREAD

**Issue by mpetito** [Kentico/content-management-sdk-net#26]
### Brief bug description

The algorithm for retrying requests fails because `HttpClient` does not support sending the same instance of `HttpRequestMessage` more than once.

https://github.com/Kentico/content-management-sdk-net/blob/1e8cf8f82dcd53f386b002a83bf139a49087ff46/KenticoCloud.ContentManagement/Modules/HttpClient/ContentManagementHttpClient.cs#L33-L39

If the `HTTP_CODE_TOO_MANY_REQUESTS` status occurs, the subequent retry attempt fails with the following error:

> The request message was already sent. Cannot send the same request message multiple times.

### Repro steps

Repro requires initiating a series of requests fast enough to trigger the 429 status code.

### Expected behavior

The request is retried using a new instance of HttpRequestMessage without error.

### Additional context

Retry policies are difficult.  You may want to consider the Polly library for implementing a retry policy.  The Polly library has correct support for retrying http requests.
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly

**Comment by petrsvihlik** [comment]
Thanks @mpetito for submitting this. I agree we should use Polly. We already use it in our other .NET SDK - the [Delivery SDK](https://github.com/Kentico/delivery-sdk-net/pull/115).

Btw - there is another issue in this repo regarding improving the retry policy: https://github.com/Kentico/content-management-sdk-net/issues/4. I'll update it with your findings.

**Comment by petrsvihlik** [comment]
should be fixed by #38
