### ISSUE TITLE
ContentManagement ExternalId URL fragments should be properly URL escaped

### ISSUE THREAD

**Issue by mpetito** [Kentico/content-management-sdk-net#27]
### Brief bug description

If an ExternalId is provided to the `ContentManagementClient` with a slash `/` then it generates an invalid endpoint url.

### Repro steps

Using the `ContentManagementClient` method `UpsertContentItemByExternalIdAsync`, provide an externalId parameter such as `"some/id"`.

You'll receive a `ContentManagementException` since the generated url appears to be `/items/external-id/some/id`.

> No HTTP resource was found that matches the request. Please read the API documentation at https://developer.kenticocloud.com.

### Expected behavior

The externalId should be escaped so as to not generate an invalid url.

### Additional context

It looks like the url templates in `EndpointUrlBuilder` are constructed using a simple string substitution without consideration for the final validity for the url.

https://github.com/Kentico/content-management-sdk-net/blob/1e8cf8f82dcd53f386b002a83bf139a49087ff46/KenticoCloud.ContentManagement/ContentManagementEndpointUrlBuilder.cs#L14

_Internal reference: DEL-2063_

**Comment by petrsvihlik** [comment]
That makes absolute sense.

@huluvu21 did you think about this scenario? Is our API prepared to consume such values? Would it be ok if we just escaped the value?

**Comment by petrsvihlik** [comment]
@mpetito we're discussing the issue internally. I'll let you know about the result.
