### ISSUE TITLE
Implement "Validate" Endpoint

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/content-management-sdk-net#3]
# Motivation
Content Management SDK for .NET currently doesn't support the `/validate` endpoint. We'd like to have it implemented.

# Solution
- [x] implement the endpoint according to the [documentation](https://developer.kenticocloud.com/v1/reference#content-management-api-validate-project)
- [ ] update the documentation documentation
https://developer.kenticocloud.com/v1/reference#content-management-api-validate-project (add another tab to the code sample)

**Comment by KristianJakubik** [comment]
Hi, I would like to work on this.

**Comment by petrsvihlik** [comment]
Great! @KristianJakubik , I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by KristianJakubik** [comment]
@petrsvihlik Invitation is accepted.

**Comment by KristianJakubik** [comment]
Hi @petrsvihlik 
I would need a help out with how to create a valid test cases for this issue. 
I assume, if I had a valid API key, I would just ask API to retrieve the valid response, which I could use as data in test cases.

However I don't have access to the API, what am I supposed to do in this case?
Thanks.

**Comment by petrsvihlik** [comment]
could you please update the docs?

**Comment by KristianJakubik** [comment]
Yes sure, will do

**Comment by petrsvihlik** [comment]
alright, I'll have our TWs update it. thanks a lot @KristianJakubik !

**Comment by petrsvihlik** [comment]
_Internal reference: CTC-329_
