### ISSUE TITLE
Switched parameters of Assert.Equal

### ISSUE THREAD

**Issue by KristianJakubik** [Kentico/content-management-sdk-net#33]
### Brief bug description

Hi,
during working on my issue, I observed, that parameters of `Assert.Equal` are switched.

https://github.com/Kentico/content-management-sdk-net/blob/2e6ef3e660eab3a0ba35561b0d189804863e4a9c/KenticoCloud.ContentManagement.Tests/ContentManagementClientTests.cs#L1156
https://github.com/Kentico/content-management-sdk-net/blob/2e6ef3e660eab3a0ba35561b0d189804863e4a9c/KenticoCloud.ContentManagement.Tests/ContentManagementClientTests.cs#L1171

When the tests fail, the result message can be pretty confusing.

### Expected behavior

`Assert.Equal(identifier.Id.ToString(), assetResult.Id.ToString());`
`Assert.Equal(identifier.Id, response.Id);`

**Comment by petrsvihlik** [comment]
Well spotted! Would you like to fix it yourself?

**Comment by KristianJakubik** [comment]
Sure :)
