### ISSUE TITLE
Improve the retry policy

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/content-management-sdk-net#4]
## Motivation
Currently, the retry policy is implemented in the [ContentManagementHttpClient](https://github.com/Kentico/content-management-sdk-net/blob/master/KenticoCloud.ContentManagement/Modules/HttpClient/ContentManagementHttpClient.cs) class.

- Currently, it doesn't work properly, as described in https://github.com/Kentico/content-management-sdk-net/issues/26.
- Also, it doesn't support any way of configuring the policy (retry attempts, enabled/disabled, etc.)
- It seems that `while ((int)response.StatusCode == HTTP_CODE_TOO_MANY_REQUESTS)` can run infinitely. it should definitely have a finite number of attempts

## Proposed solution
Add a capability of dealing with transient network outages via the following retry policy:

* Let the client code define a maximum amount of retry attempts, preferably via the ContentManagementOptions class.
* If not specified in the options, the retry policy should be enabled by default.
* If specified, the Delivery client should retry in exponential retry intervals.
* When all retry attempts fail, the SDK should notify the client code about it, preferable via an exception.
* Use Polly library
* Add unit tests validating the retry policy works as expected

Sample implementation in Delivery SDKs:
- [.NET](https://github.com/Kentico/delivery-sdk-net/pull/115) (Polly)
- [PHP](https://github.com/Kentico/delivery-sdk-php/commit/f402059504cdc2a23ec8bf368ffdc14e8426a2af)
- [Java](https://github.com/Kentico/delivery-sdk-java/pull/54)

**Comment by petrsvihlik** [comment]
@mpetito would you be willing to help us with this issue?

**Comment by petrsvihlik** [comment]
fixed in #38
